redhat-performance/JetSki

ansible-ipi-install/group_vars/all.yml
ansible-ipi-install/inventory/jetski/hosts
ansible-ipi-install/playbook-jetski.yml
ansible-ipi-install/roles/bootstrap/tasks/01_install_packages.yml
ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
ansible-ipi-install/roles/network-discovery/tasks/main.yml
ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml

Currently the playbook-jetski.yml and the roles are written such
that the playbook only works when run from localhost.
The main motivation behind this change is to enable JetSki to be run from a remote host instead of implicit localhost, for the purposes of CI/Jenkins environments. Currently certain plays in playbook-jetski.yml run on implicit localhost and all the facts set on the implicit localhost are conveniently accessed using hostvars['localhost'] in several roles. 
When the playbook/roles were written and the way it was written did not necessitate the need to actually be able to set a different remote other than localhost (for running the bootstrap and add-provisioner roles) as for the most part the `provisioner` host is …

Allow playbook execution from remote host

---

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml

This is needed because when running from the same remote [orchestration] host
although we specificy a new cloud to deploy on, since the location being checked on
remote is {{ansible_user_dir}}/ocpinv.json and it already exists from a previous
deployment, it could be used for the current deploy.
This patch defaults to using a temp location if orechestration is being done from a remote
host, and sticks to {{ playbook_dir }}/ocpinv.json when the localhost is the orchestration
host, for user convenience (if they wanted to manually edit the inventory file and have
JetSki consume it on a subsequent run). …

Support download inventory to tempfile

---

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml

Earlier, the creation of the tempdir had to be done regardless
of whether or not the playbook ran on the localhost or some remote
host as the ternary condition would fail otherwise.
- Versions:
- Hardware:

Replace ternary filter with regular if/else

---

ansible-ipi-install/approve_csr.bash
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

The change:
- A script is run concurrently to automatically approve CSRs (Certificate Signing Requests).
- It loops until the expected number of workers are "Ready" in `co get nodes`. Once they are "Ready" instead of "NotReady", no more CSR approvals should be needed, it exits, and in my testing it worked.
- The script is copied to the server right before it is run, then it is run using the shell Ansible module. It is not run using the script module because that does not support async tasks.
- It does not run when there are 0 workers.
If you want, I can make the script self-deleting.
Motivation behind this change:
- CSRs are not getting approved in our lab environment for some reason, so this workaround will get the job done without the user needing to manually wait and approve them. …

Auto-approve CSRs

---

ansible-ipi-install/approve_csr.bash
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

This change does a few things:
- Sets an environment variable to try to make sure it can access the kubeconfig
- Puts the script in a new location so that it does not get deleted before it finishes
- Adds a debug message so the user can view the script's result file
Issue: #42 
This was tested on Cloud18. JetSki was set with reprovision set to true.
Cloud18 has 6 nodes, so only two worker nodes are being tested with the script.
Since this is not consistently reproduced, it would be best to have several people test this, ideally with more than 2 workers.

Improve reliability of auto-approve CSRs

---

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

This commit uses the newly added return codes in badfish to
figure out if the iDRAC is ready to accept commands to change
boot order, before attempting to do so. This should fix most of
ALIAS installation issues.
Fixes: #19
- Versions:
- Hardware:

Wait until drac is responsive before setting boot order

---

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

Right now we have two tags clearjobs and bootorder.
This commit does the following:
1. Replace the clearjobs tag with bootorder tag since
that is also needed only when setting boot order.
2. Add the bootorder tag to power on master/worker nodes
tasks as they need to be powered on only for badfish
to work, so if not setting bootorder, we can skip them
3. Adds the bootorder tag to the task that does --check-boot
since that task is also not needed when not setting boot
order
Please describe the tests that you …

Consolidate bootorder tag

---

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
ansible-ipi-install/roles/shared-labs-prep/vars/main.yml

RDO doesn't provide gpg checks for their packages, ansible yum module defaults to enabling gpg check. This PR breaks out the RDO packages and turns off gpg check for those packages. 
Fixes # [slack chats](https://coreos.slack.com/archives/CFVMERKJ9/p1601901276101300)
- Versions:
- Hardware:

turn off gpgcheck for rdo packages

---

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml

e541aeda1522bc3ebd7b28a72e327bd1b1c56260 which added the mechanism
to make sure all nodes being used are part of the user's actual cloud
allocation broke the workflow of being able to use a custom inventory.
This commit fixes it.
- Versions:
- Hardware:

Fix issue with using custom inventory

---

ansible-ipi-install/inventory/jetski/hosts
ansible-ipi-install/inventory/shared_labs/hosts

This commit does two things:
1. Gets the new `redfish_inspection` option and sets it to
false by default to force IPMI installs
2. Also `setsdisable_bmc_certificate_verification` to true
to disable certificate verification if we switch to redfish
in future.
- Versions:
- Hardware:

Update inventory after upstream rebase

---

ansible-ipi-install/inventory/jetski/hosts
ansible-ipi-install/inventory/shared_labs/hosts
ansible-ipi-install/roles/shared-labs-prep/defaults/main.yml
ansible-ipi-install/roles/shared-labs-prep/files/99_openshift-cluster-network.yaml
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

This patch let user to enable OVN `hybridOverlayConfig` plugin in cluster, which enables additional overlay network for peers without OVN. This is mainly required for BigIP implementation.
Fixes #77 

Add manifest file to enable OVN hybrid plugin

---

ansible-ipi-install/roles/bootstrap/defaults/main.yml
ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml

Fixes issue #87
The first commit fixes the problem that the AMD server types were not defined in the inventory
so that various list vars in roles/bootstrap/tasks/10_load_inv.yml were not getting defined.
However, this exposed a bug in the with_items loops - if the loop body was never executed, the
assignment to the list variable was never done and so the list variable was undefined when referenced.
This problem was fixed by initializing such variables with a set_fact statement at the top, and
then removing the "default([])" filter from the loop body assignment statement.  This makes the code
more readable as well.
Finally, there is a check at the end for all masters being of same machine type as each other and 
same machine type as the provisioner host.   I was given a cloud for which …

Amd reservation

---

ansible-ipi-install/roles/bootstrap/defaults/main.yml
ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
ansible-ipi-install/roles/network-discovery/tasks/main.yml
ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml

A minor patch to let user choose heterogeneous prov+master nodes within a cloud, now prov can be a non-telco class server.
Works for all model except SM 1029U due to different interface name for TRTP and TN10RT types so masters and prov should be the same unless there is a way to differentiate these models based on FQDN.
- Versions: OCP 4.7
- Hardware: Prov - SM 1029P  and Master 3 Dell FC640

patch for prov-master homogeneity constraint

---

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2

Disable public nic to avoid DHCP conflicts using `MachineConfig` is the recommended way instead of `Ignition` file. Removing ignition file customization and adding new manifest file as described in issue.
Fixes #62 
- Versions: 4.7.0-0.nightly-2020-11-18-085225
- Hardware: Dell FC640

machine config to disable public nic

---

ansible-ipi-install/roles/shared-labs-prep/files/99_openshift-cluster-network.yaml

4.7 nightly build fails with below network operator error if OVN hybrid plugin is enabled.
```
Error while trying to update operator configuration: could not update object (operator.openshift.io/v1, Kind=Network) /cluster: Network.operator.openshift.io "cluster" is invalid: spec.defaultNetwork.ovnKubernetesConfig.hybridOverlayConfig.hybridClusterNetwork: Invalid value: "null": spec.defaultNetwork.ovnKubernetesConfig.hybridOverlayConfig.hybridClusterNetwork in body must be of type array: "null"
```
- Versions: 4.7.0-0.nightly-2020-12-14-080124
- Hardware: FC640

OVN hybrid fix for 4.7 deployment

---

ansible-ipi-install/roles/network-discovery/tasks/main.yml

The tasks for setting bm and provisioning interfaces
fail otherwise, when there isa  VLANed interface on the
provisioning node.
- Versions:
- Hardware:

Exclude vlaned interface from list

---

ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml

Userful when worker_count is not defined in group_vars/all.yml
in which case it defaults to all nodes except first 3 which are used
as masters. The worker_count var is already set if undefined on the
orchestration host, this just sets the fact on the provisioner as well.
- Versions:
- Hardware:

Set worker_count deployment fact

---

ansible-ipi-install/roles/scale-node-prep/tasks/main.yml
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

Recent trouble with Supermicro(few models/server) that the node is not PXE'ing consistently during Ironic inspection, this often happens during a redeployment of cluster. As a temporary workaround, power off the node before Jetski deployment helped in most of the cases.
It may be due to the Ironic PXE boot WITHOUT persistent option is not effective in some servers. 
This patch makes sure that server is set to PXE boot WITH persistent option by rebooting once before handing over the server to installer. 
- Versions:
- Hardware:

reboot supermicro node once after set to pxe

---

README.md
ansible-ipi-install/playbook-jetski-scaleup.yml
ansible-ipi-install/roles/scale-worker/tasks/10_bmc_secrets.yml
ansible-ipi-install/roles/scale-worker/tasks/20_create_bmh.yml
ansible-ipi-install/roles/scale-worker/tasks/30_scale_machinesets.yml
ansible-ipi-install/roles/scale-worker/tasks/main.yml
ansible-ipi-install/roles/scale-worker/templates/bare-metal-host.yaml.j2

1. Consistent names for nodes and `BareMetalHost` resources suffixed with model number
2. Playbook will exclude if any nodes failed during `Introspection` stage and proceed with remaining nodes for `provisioning`
3. Updates `deployed` and `non-deployed` nodes accordingly so that failed nodes can be reattempted
- Versions: 4.7.0 GA
- Hardware: Dell FC640

scaleup worker patch

---

ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2

Error in `if` condition to identify the release when the version is set to `latest-*`, this affect ignition file generation  due to invalid machine configuration file.
```sh
Failed to create "50-disable-lab-public-nic-master.yaml" machineconfigs.v1.machineconfiguration.openshift.io/50-disable-lab-public-nic-master -n : MachineConfig.machineconfiguration.openshift.io "50-disable-lab-public-nic-master" is invalid: spec.config.ignition: Required value
```
- Versions:
- Hardware:

fix ignition version logic

---

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

After rebooting provisioner, cluster connectivity is lost due to `dnsmasq` service being failed to start while booting because of the offline network interface(service listening on baremetal bridge). 
The `dnsmasq` service is scheduled(by default) to start even before the network comes online, its changed now to start after `network.online`. 
Courtesy: Sai found the fix.
- Versions:
- Hardware:

Dnsmasq to start after network is up

---

ansible-ipi-install/roles/scale-node-prep/tasks/main.yml
ansible-ipi-install/roles/shared-labs-prep/tasks/20_set_director_mode.yml
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

Badfish command to set Director boot order occasionally fails due to iDRAC problem, its better to attempt a racreset and re-apply boot order with in rescue tasks rather than failing entire play. 
Sometime this failure gets in to a loop at each execution for different server and never cross this prep task.
- Versions:
- Hardware:

Rescue badfish tasks

---

ansible-ipi-install/roles/bootstrap/defaults/main.yml
ansible-ipi-install/roles/network-discovery/tasks/main.yml

Fix to handle R640 public interface name discrepancy for Mellanox NIC. This fix will disable both `eno1` as well as `eno1np0` for R640 nodes.
https://projects.engineering.redhat.com/browse/SCALELAB-1116
- Versions: 4.7.7
- Hardware: R640

r640 pub if name change

---

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml

OCp 4.8 installer seems to require a version of libvirt
that is available in RHEL 8.3. Bumping to RHEL 8.3 for all
versions as it should previous versions should also work on RHEL 8.3.
- Versions:
- Hardware:

Bump RHEL version on provisioner

---

README.md
ansible-ipi-install/playbook-jetski-scaleup.yml
ansible-ipi-install/playbook-jetski.yml
ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
ansible-ipi-install/roles/scale-bootstrap/tasks/10_load_old_inv.yml
ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml
ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml

Airflow CI job runs within a short-living pod and we can't really use them to store JetSki created files(ocpdeployed.json & ocpnondeployed.json) to scaleup worker later. 
This change will now create and store the files directly in the provisioner node, so it can be accessible from any ansible host/pod. 
- Versions:
- Hardware:

moved scaleup result files to provisioner node

---

ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2
ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.nm.conf.j2
ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.sctp-module.yaml.j2

Additional `NetworkManager` configuration to unmanage all the unwanted interfaces, as describe in the bz https://bugzilla.redhat.com/show_bug.cgi?id=1984708
Manifest file would be like,
```
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
labels:
machineconfiguration.openshift.io/role: master
name: 50-disable-lab-public-nic-master
spec:
config:
ignition:
version: 3.1.0
storage:
files:
- contents:
source: data:text/plain;charset=utf-8;base64,REVWSUNFPWVubzEKQk9PVFBST1RPPW5vbmUKT05CT09UPW5vCg==
filesystem: root
mode: 0644
path: /etc/sysconfig/network-scripts/ifcfg-eno1
- contents:
source: data:text/plain;charset=utf-8;base64,W2tleWZpbGVdCnVubWFuYWdlZC1kZXZpY2VzPWludGVyZmFjZS1uYW1lOmVubzEK
filesystem: root
mode: 0644
path: …
```

networkmanager keyfile to disable interfaces

---

ansible-ipi-install/roles/scale-node-prep/tasks/main.yml
ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml

Update in the badfish code cause the command to fail due to a missing library, it is included now as per @grafuls suggestion. 
Fixes #186 
- Versions:
- Hardware:

badfish missing library

---

README.md
ansible-ipi-install/group_vars/all.yml
documentation/ipi-install/modules/ipi-install-upstream-select-an-openshift-installer-release-from-ci-development.adoc

URLs in documentation for ci.openshift.org were broken after app.ci was decommissioned about April 2021. This replaces those URLs with working ones.
Fixes #202 
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] This change is a documentation update
- Versions:
- Hardware:
- [ x ] I have performed a self-review of my own code
- [ x ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.

corrects broken ci.openshift.org URLs

---

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
ansible-ipi-install/roles/bootstrap/vars/main.yml

As stated at https://github.com/redhat-performance/JetSki/issues/226#issuecomment-1180491616, we can remove this task since the Badfish image is already pulled as part of `podman run`. Also adding the flag `--pull=always` to emulate the previous behavior that had `force: true`
Fixes #226 

Remove podman module

---

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml

Fixes errors that look like this when there is a space in the release name
```
[2022-08-30, 19:21:08 UTC] {subprocess.py:92} INFO - TASK [bootstrap : set os_install] **********************************************
[2022-08-30, 19:21:08 UTC] {subprocess.py:92} INFO - Tuesday 30 August 2022  19:21:08 +0000 (0:00:00.049)       0:00:16.153 ********
[2022-08-30, 19:21:08 UTC] {subprocess.py:92} INFO - [0;31mfatal: [localhost]: FAILED! => {"msg": "Version comparison failed: '<' not supported between instances of 'str' and 'int'"}[0m
```
- Versions:
- Hardware:

fix set os_install error

---

ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.machineconfig.yml.j2
ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.udev-pubnics.rules.j2

Deployment of OCP on r650 hardware was having issues with IP assignment on the private and public interfaces, required for the lab setup.
It seems that during startup RHCOS configures all interfaces using DHCP. Configuring the public NIC as unmanaged by NetworkManager later during statup does not have the desired effect. We therefore disable the public NIC with a new udev rule.
- Versions: 4.10 and 4.11
- Hardware: r650

Use udev to disable public NICs on startup
