redhat-performance/JetSki

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
Closes: #3
- Versions:
- Hardware:
=> Change task name for alias

README.md, ansible-ipi-install/group_vars/all.yml
=> Minor docs updates

README.md
=> Readme updates on running playbook

README.md, ansible-ipi-install/group_vars/all.yml, ansible-ipi-install/roles/bootstrap/files/Dockerfile, ansible-ipi-install/roles/bootstrap/files/foreman.yml.j2, ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
1. Move away from hammer_host
2. Run hammer commands from a container
3. Also fixes the problem of the code needing hammer_host and provisioner
root passwords to be the same
4. Update README and also sample `group_vars/all.yml` files
5. Supports both Scale and ALIAS labs
Fixes: #2
Fixes: #4
- Versions:
- Hardware:
=> Containerize hammercli

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
=> Support custom extcidrnet

ansible-ipi-install/roles/bootstrap/tasks/25_copykeys.yml
=> Use {{ ansible_ssh_key }} when copying keys

README.md
inventory/hosts -> inventory/jetski/hosts on line 514 README.md
- Versions:
- Hardware:
=> Fix typo on line 514 README

README.md, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
Also minor typo fix for README
Signed-off-by: Sai Sindhur Malleni <smalleni@localhost.localdomain>
- Versions:
- Hardware:
=> Remove un-needed privelege escalation in shared labs role

ansible-ipi-install/roles/bootstrap/files/Dockerfile, ansible-ipi-install/roles/bootstrap/vars/main.yml
This is a security best practice.
Fixes: #37
- Versions:
- Hardware:
=> Use qualified image names for container images

README.md, ansible-ipi-install/group_vars/all.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.dnsmasq.conf.j2
Closes: #39
- Versions:
- Hardware:
=> Enable deployment with Jumbo Frames

README.md, ansible-ipi-install/inventory/jetski/hosts
Also add 4.5 to list of tested versios in README.md
- Versions:
- Hardware:
=> Add default source for NTP in inventory for JetSki

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/vars/main.yml
Fixes: #46
- Versions:
- Hardware:
=> Use the right relative path for config/idrac_interfaces.yml

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/inventory/shared_labs/hosts
=> Update inventory files

ansible-ipi-install/roles/shared-labs-prep/tasks/10_redfish_queue.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/vars/main.yml
Included a rescue task for Badfish API failure when it tries to clear the job queues, this task will attempt to make an iDRAC reset.
Fixes #52
Tested on BM(FC640)
- Hardware: Dell FC640
=> Handling Badfish command execution error

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
Additional Inventory validation to fix the issue
Fixes #58 
Tested with issue scenarios,
=> Adding inventory validation tasks to fix an issue

README.md
Also adds 4.6 to list of tested releases.
Closes: #63
- Versions:
- Hardware:
=> Add Contribution guide in README.md

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
=> Update pip in venv to fix failing badfish installs

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
=> Enable user configured baremetal network

ansible-ipi-install/roles/bootstrap/templates/node_inv.j2
=> Add else condition to fix template issue

Dockerfile, README.md, ansible-ipi-install/playbook-jetski.yml, ansible-ipi-install/roles/bootstrap/defaults/main.yml, ansible-ipi-install/roles/bootstrap/tasks/01_install_packages.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml, ansible-ipi-install/roles/network-discovery/defaults/main.yml, ansible-ipi-install/roles/network-discovery/tasks/main.yml, ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
=> Enable Supermicro deployments and heterogeneous deployments

ansible-ipi-install/playbook-jetski-scaleup.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/bootstrap/templates/node_inv.j2, ansible-ipi-install/roles/scale-bootstrap/defaults/main.yml, ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml, ansible-ipi-install/roles/scale-node-prep/tasks/main.yml
To support heterogeneous worker nodes scaling. 
Fixes - #81 
=> scale up hetero worker nodes

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/inventory/shared_labs/hosts
=> Increase prov_dhcp_range now that we have /21

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
=> fixed hetero when conditions for alias lab

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/inventory/shared_labs/hosts
=> Increase extnetcidr to /21 to match provisioning net

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml
Scale worker tasks when condition has to be updated for alias lab, to fix an issue seen earlier.
- Versions: OCP 4.7
- Hardware: Dell FC640
=> Scale worker tasks for alias lab

ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
=> set supermicro boot order to PXE UEFI

Dockerfile, README.md, ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
One issue, and one potential issue are fixed in this pull request.
The issue fixed is that it appears that installing the badfish requirements.txt file now requires it to build some things, so those dependencies were added.
The other issue is a line was commented out that configured a file for foreman. That line has been uncommented with the proper path.
I have tested building the Dockerfile using Podman on Fedora.
However, as I do not have access to a baremetal environment, the addition of the j2 line is untested.
=> Container Fixes

README.md, ansible-ipi-install/group_vars/all.yml, ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml
This is needed to effectively consume pullsecret in group_vars when exported
as an environment variable (in jenkins for example).
- Versions:
- Hardware:
=> Use to_json for pullsecret

README.md, ansible-ipi-install/roles/bootstrap/defaults/main.yml, ansible-ipi-install/roles/bootstrap/vars/main.yml
badfish invocations fail sometimes without this
- Versions:
- Hardware:
=> Add DNS server param for badfish

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/inventory/shared_labs/hosts, ansible-ipi-install/roles/installer/templates/install-config.j2
We carry these custom values in JetSki inventory and install-config.j2.
Also helps with the ipv6 efforts.
- Versions:
- Hardware:
=> Bring parity between with  install-config.j2

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/inventory/shared_labs/hosts, ansible-ipi-install/roles/shared-labs-prep/defaults/main.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.dnsmasq.conf.j2
=> Dual-Stack PR after rebasing with upstream

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/network-discovery/tasks/main.yml
=> Handle yet another R640 corner case

README.md, ansible-ipi-install/group_vars/all.yml, ansible-ipi-install/roles/bootstrap/tasks/01_install_packages.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
Enabling an option to specify provisioner node from a cloud, this is useful for CI as it is not easy to edit the ocpinv.json file in the middle of the execution. 
- Versions:
- Hardware:
=> option to pick provisioner host

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
=> conditional corner case for R640s

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml, ansible-ipi-install/roles/network-discovery/tasks/main.yml, ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml, ansible-ipi-install/roles/set-deployment-facts/tasks/main.yml
=> prov_node options to scaleup and other roles

ansible-ipi-install/roles/bootstrap/files/Dockerfile
I could reproduce the issue in centos7, updated them to use centos:8. 
Fixes #142 
- Versions: 
- Hardware: Dell R640
=> updated hammer image

ansible-ipi-install/ci/Dockerfile, ansible-ipi-install/ci/README.md, ansible-ipi-install/roles/bootstrap/tasks/01_install_packages.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
CI fixes, mainly to run the playbook inside a container as a non-root user. 
- Versions:
- Hardware:
=> ci user privileges and fixes

ansible-ipi-install/roles/bootstrap/defaults/main.yml
=> Change ALIAS wiki location

ansible-ipi-install/roles/bootstrap/vars/main.yml
=> Change badfish image location to quay.io

ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml
=> missing privilege escalation

ansible-ipi-install/inventory/jetski/hosts, ansible-ipi-install/roles/shared-labs-prep/files/99_local_gateway_ovn.yaml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml
We need this because from 4.8+ shared gateway mode is set by default yet
for BM deployments we care about local gateway mode.
- Versions:
- Hardware:
=> Default to OVN local gateway mode

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
Intermediate patch to handle RHEL 8.4 upgrade.
- Versions:
- Hardware:
=> script to update rhel for latest ocp

ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml
Intermediate patch to handle RHEL 8.4 upgrade.
- Versions:
- Hardware:
=> os upgrade with reboot

ansible-ipi-install/roles/bootstrap/defaults/main.yml, ansible-ipi-install/roles/bootstrap/tasks/20_reprovision_nodes.yml, ansible-ipi-install/roles/bootstrap/tasks/40_prepare_provisioning.yml
Provides greater flexibility
- Versions:
- Hardware:
=> Provisioning improvements

ansible-ipi-install/ci/Dockerfile, ansible-ipi-install/playbook-jetski.yml, ansible-ipi-install/roles/bootstrap/tasks/01_install_packages.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/templates/ocp4-lab.nm.conf.j2, ansible-ipi-install/roles/shared-labs-prep/vars/main.yml
Few changes for airflow CI execution.
- Versions:
- Hardware:
=> fixes for airflow

ansible-ipi-install/roles/bootstrap/defaults/main.yml
Included new Dell server type, added below interface based on the scale lab doc http://docs.scalelab.redhat.com/trac/scalelab/wiki/ScaleLabTipsAndTricks#RDU2ScaleLabPrivateNetworksandInterfaces
Fixes #189 
- Versions: OCP 4.8
- Hardware: Dell R640 and R650
=> new dell server type

ansible-ipi-install/playbook-jetski-scaleup.yml, ansible-ipi-install/playbook-jetski.yml, ansible-ipi-install/roles/network-discovery/tasks/main.yml, ansible-ipi-install/roles/scale-bootstrap/tasks/main.yml, ansible-ipi-install/roles/scale-node-prep/tasks/main.yml, ansible-ipi-install/roles/scale-worker/tasks/20_create_bmh.yml, ansible-ipi-install/roles/scale-worker/tasks/30_scale_machinesets.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/vars/main.yml
- Ignore failures of `machinesets` replicas after scaleup
- Check available `worker` count to verify state instead
- Delete failed hosts (due to Introspection error)
- Quit playbook when `worker_count` is already met
- Versions:
- Hardware:
=> modification  for CI

ansible-ipi-install/roles/scale-node-prep/tasks/main.yml, ansible-ipi-install/roles/scale-node-prep/vars/main.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/10_redfish_queue.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/20_set_director_mode.yml, ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml, ansible-ipi-install/roles/shared-labs-prep/vars/main.yml
Latest Badfish has some issues on using virtual python environment and venv will [not be supported](https://github.com/redhat-performance/JetSki/issues/186#issuecomment-982666646) in the long run. 
error:
```
File \"./src/badfish/badfish.py\", line 24, in <module>\n    from src.badfish.helpers.async_lru import alru_cache\nModuleNotFoundError│···································: No module named 'src'", "stderr_lines": ["Traceback (most recent call last):", "  File \"./src/badfish/badfish.py\", line 24, in <module>", "    from src.badfish.helpers.async_lru import alru_cache", "ModuleNotFoundError: No module named 'src'"], "stdout": "", "stdout_lines": []}
```
Updating this to use podman image instead.
Please describe the tests that you …
=> Badfish patch

ansible-ipi-install/group_vars/all.yml, ansible-ipi-install/playbook-jetski.yml, ansible-ipi-install/roles/add-provisioner/tasks/main.yml, ansible-ipi-install/roles/bootstrap/tasks/10_load_inv.yml, ansible-ipi-install/roles/post-install/defaults/main.yml, ansible-ipi-install/roles/post-install/tasks/70_deploy_dittybopper.yml, ansible-ipi-install/roles/post-install/tasks/main.yml, ansible-ipi-install/roles/post-install/templates/cluster-monitoring-config.yml.j2
=> add optional post install tasks

ansible-ipi-install/roles/network-discovery/tasks/main.yml
Removed an extra space in yaml.
- Versions:
- Hardware:
=> corrected yaml indentation 
